### PR TITLE
Removed VAS implementation

### PR DESCRIPTION
**Pull request by ultranoobian**
- Lots of whitespace trimmed
- Removed references to VAS and made VA the primary source of weaponry.

---

This change is [Reviewable](https://reviewable.io/reviews/duws-r-team/duws-r/123)

### CODE REVIEW

**Comment by ultranoobian** [comment]
VAS files were removed.

**Comment by fritogotlayed** [comment]
@ultranoobian Sorry, I just noticed this PR. At a quick glace I noticed we're killing a bunch of header files? Are these no longer needed? I don't have ArmA installed right now to verify.

**Comment by ultranoobian** [comment]
@fritogotlayed So yeah, I killed off all of the references to the Virtual Ammobox System, and made sure that ammoboxs, FOBs, etc had their text updated, description.ext, etc.
So I removed the VAS files.

I'm actually reconsidering this pull request since it messed up so much of the trailing whitespace and isn't really that clean, and have to rebase to keep the whitespace to format at a later date.

**Comment by ultranoobian** [comment]
Now I've configured atom to not trim whitespace and I've separated the modifications and deletions for easier reading.

**Pull request closed without merging**
