### PR TITLE
Fixed New Heli System

### LINKED ISSUE #79: Make the Helo Taxi experience more realistic
```
Emton 6 hours ago  
Hey I have a request. I was joyed to find out DUWS has the helicopter taxi because I can 
use that for evacuation after I get my chopper shot down. But it could be reworked to not 
be so weird. For one when you request the chopper it should spawn at home base to make
the journey to your location, instead it seems to spawn in the air fairly close to you, when it
came to me it was actually in the direction of the enemy, so it would be a lot more realistic
if it spawned at the home base. Second, I see there is an option to "detonate taxi" well I 
understand this is if you want to cancel the taxi but this seems a little extreme, if there was 
an option to "cancel evac" and when you activate that the chopper simply returns to home 
base where it spawns, that would be ideal for immersion. I actually hit the detonate after it 
dropped me at home base and it destroyed everything it was hilarious but I prefer 
immersion.
 
Emton 6 hours ago  
So to wrap up I think the helicopter taxis should work like this:
When you call for taxi it spawns that chopper within 100m of the base and takes off from 
there. If you cancel the evac the chopper returns to it's spawn point and you lose the CP 
you spent. After the chopper drops you off at your location it waits there until you call it 
again (for more CP) or until you board it and give it a new destination.

I think that's a pretty simple way of doing it but would be a lot more realistic. I want to care 
about the taxi and keep it alive if it saves me some CP, not just blow it up after I don't need 
it ya know what I mean?
```

### PR DESCRIPTION
**Pull request by bolbies**
### Issue
Fixes #79 

### Summary
Fixed previous pull request.

### CODE REVIEW

**Comment by fritogotlayed** [comment]
@bolbies You know you don't have to close the "old" pull request. When you commit code to the same branch it'll automatically update the pull request with the new version. :-D It's one of the pretty sweet things with git.

**Comment by fritogotlayed** [comment]
@bolbies Pretty sweet. Thanks for tackling this :smile:

**Comment by fritogotlayed** [comment]
@bolbies I got the comment below. I haven't dug too far into it. Is this something you can look at? 

vSure 3 hours ago  
My heliocopter Taxi keeps getting bugged and is hovering in place, refusing to move/land/anything. Often happens when I come back from a mission with it to my Main Base then head out a few minutes later. Any idea how to fix or a work around I can use until then? :(

**Comment by bolbies** [comment]
I have no idea what could be causing that but I'll look into it. Can you ask what missions cause this? Were there any errors in his RPT?

**Comment by fritogotlayed** [comment]
@bolbies I directed vSure to talk to us on the issue rather than here on this PR. #79

**Pull request merged**
