### PR TITLE
Sell Resources and Taxi Fixes

### PR DESCRIPTION
**Pull request by bolbies**
Very basic "Sell Resource" script. It only checks the condition of the
engine as of right now. Wheels are finicky but I'll figure something out
eventually. I'll also eventually add rear rotor for helis and etc for
certain vehicles. As for the taxi, you no longer have to call it from
the base first. It'll fly straight there on its first run.

### CODE REVIEW

**Comment by bolbies** [comment]
Oh and what do you guys think the mission reward vehicles (teleporter strider, supply truck, etc) should be worth? I completely forgot about those.

**Comment by fritogotlayed** [comment]
I think you'll need to rebase up. I just merged the updated vehicle list :-/. What are you referring to with the mission reward? Shouldn't that be a separate pull request? Also, thanks a ton for contributing once again!

**Comment by fritogotlayed** [comment]
@bolbies I just looked at the graph and it looks like you're pretty out of date :-) https://github.com/DUWS-R-Team/DUWS-R/network

**Comment by bolbies** [comment]
Yeah I know school has kept me very busy for a while. I'll get on the updated vehicles. As for the mission rewards, I'm referring to the strider that serves as a mobile teleporter and the supply truck you have to obtain.

**Comment by fritogotlayed** [comment]
No worries. Work has kept me pretty busy as well. Besides, school comes first :-)

**Comment by bolbies** [comment]
So apparently my branch is outdated. How can I update it? Do I merge them?

**Comment by fritogotlayed** [comment]
Hey. I'm not sure what tool you're using to manage your Git repo so I'm going to go with Git Bash. 

** This whole section is 'one time' configuration **
First we'll make sure that your local computer knows about the central code repository
* `git remote -v` <-- Lists all the remotes your computer knows about. 
* At this point you'll want to make sure there are the following two lines in the output
  * `upstream        [[something here]] (fetch)`
  * `upstream        [[something here]] (push)`

** Now we're on to what you really want to do
Next make sure you don't have any changes on your branch
* `git checkout DUWS_additions` <-- This puts you on your DUWS_additions branch
* `git status` <-- Make sure this says "working directory clean"  

Then we'll sync up your local branch `master` and your `origin` branch master with upstreams `master`
* `git checkout master` <-- put you on your local master
* `git fetch upstream` <-- find out what changes are in upstream
* `git rebase upstream/master` <-- sync up local master with upstream master
  * At this point you should get a clean rebase. If you don't the branch name in git bash will say something like (master | REBASING) if I recall correctly. If it does that you'll most likely either need to abort the rebase or figure out how to merge the changes. 
* Assuming no conflicts... `git push origin master:master` <-- make github's `master` branch sync with your local computer `master` branch

Wow, that was a bunch. The nice thing is that getting your `DUWS_additions` branch in sync is pretty much the same process. I can guarantee you that you'll have conflicts here though. Lets get things synced up here now...
* `git checkout DUWS_additions` <-- switch back to the "additions" branch
* `git rebase master` <-- note this one doesn't say "upstream/master". That is because at this point we've already made sure that your local master is in-sync with upstreams master. Now we can use our local master as the point with which to rebase.
  * At this point you'll definitely have the git bash name say something like "(DUWS_additions | REBASING). 
* You can start merging your changes by using whatever merge tool you are comfortable with. I don't recall what the default merge tool is for Git Bash but you can run it by typing in `git mergetool`. It will list what files have conflicts and display each set of files to you. You just press enter and the merge tool with expand letting you perform the merge :smile: 

Now, I know all of that is a bunch of information to take in. If you'd like and/or you get stuck feel free to ping me on steam and we can look at the merge together. I have a friends child's birthday party to go to so I'm going to be away from the house a good chunk of the day. If you'd like though I usually use https://www.join.me to share screen. It's free and pretty light weight so I usually use it with my parents who are not computer savvy.

**Comment by bolbies** [comment]
Idk what happened but github won't let me do anything anymore. It says it can't sign out of the branch because of a merge error and that I have 106 files to commit. Any ideas?

**Comment by bolbies** [comment]
Use new pull request

**Pull request closed without merging**
